service: thirdwavelist

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  profile: default
  stage: v1
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - es:*
      Resource: "arn:aws:es:us-east-1:597411703460:domain/cafe"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:table/thirdwavelist-v1-cafe*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem      
      Resource: "arn:aws:dynamodb:us-east-1:*:table/thirdwavelist-v1-roaster*"
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100
  apiKeys:
    - thirdwavelist-v1-key

functions:
  createCafes:
    handler: handler.createCafes
    events:
      - http:
          path: cafe
          method: post
          private: true
          cors: true

  listCafes:
    handler: handler.listCafes
    events:
      - http:
          path: cafe
          method: get
          private: true
          cors: true

  lookupCafe:
    handler: handler.lookupCafe
    events:
      - http:
          path: /{city}/{cafe}
          method: get
          private: true
          cors: true

  deleteCafe:
    handler: handler.deleteCafe
    events:
      - http:
          path: cafe/{id}
          method: delete
          private: true
          cors: true
    
  listRoasters:
    handler: handler.listRoasters
    events:
      - http:
          path: roaster
          method: get
          private: true
          cors: true

  createRoasters:
    handler: handler.createRoasters
    events:
      - http:
          path: roaster
          method: post
          private: true
          cors: true
          
resources:
  Resources:
    CafeDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: uid
            AttributeType: S
        KeySchema:
          - AttributeName: uid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "thirdwavelist-v1-cafe"
    RoasterDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: uid
            AttributeType: S
        KeySchema:
          - AttributeName: uid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "thirdwavelist-v1-roaster"
